### PR TITLE
Fix for empty schema

### PR DESCRIPTION
**Pull request by roman2861**
In some cases snowplow can get empty/corrupted schema
This fix should create a fallback for that cases

### CODE REVIEW

**Comment by denisov-vlad** [comment]
@roman2861 Thanks. Could you provide payload which throws an error? 

I'm not sure that we shouldn't log this case.

**Comment by roman2861** [comment]
That request returns 500 error, which should happen in any case from my point of view.

**Comment by roman2861** [comment]
@denisov-vlad did you get an opportunity to check my request? Hope for merge to use it in our project

**Comment by denisov-vlad** [comment]
Hi @roman2861. I've checked your error and it happens because the schema can't be parsed into event names. Your solution is to skip those types of events, but I don't like that.

You can pass the schema like this `iglu:dev.snowplow.simple/custom_data/jsonschema/1-0-0`

So, the JS code could be written in that way:

```
snowplow('trackSelfDescribingEvent', {
  event: {
    schema: 'iglu:dev.snowplow.simple/custom_data/jsonschema/1-0-0',
    data: {
        pageScroll: 25,
    }
  }
});
```

**Pull request closed without merging**
